### ISSUE TITLE
マルチプレイヤーでアクションが反映されない

### ISSUE THREAD

**Issue by aspennn** [firis-games/LittleMaidAvatar#2]
#1 の続き

### 環境
* Minecraft Version: 1.12.2
* Forge Version: 14.23.5.2854
* Mod Version
LMLibrary 1.1.3
LittleMaidReengagedFP 9.3.4.fp.054
LittleMaidAvatar 1.2.0
* Java Version: Java 8

>LMアバターのマルチモデル同期処理は下記の3パターンがあります。
>・マルチモデル・アクションの同期をしない
>・マルチモデルのみ同期する
>・マルチモデル・アクションの両方を同期する
>デフォルトでは2番目のマルチモデルのみ同期する設定になっていますので設定を変更していない場>合はアクションは同期されません。

サーバークライアント共に同期設定が有効になっています
B:LittleMaidAvatarMulti.SyncAction=true
B:LittleMaidAvatarMulti.SyncModel=true
ちなみにデフォルトは1番ではないでしょうか？

### 状況など
テンキー1を押してLMアバターのAction1を実行したとして
SyncPlayerModelClientのsendPacketToServerで送信される時の
nbtのactionが0になっていて
サーバーや他のクライアントにアクションが反映されていません。
他のアクションも同様です。
環境依存とかでなければこれはサーバー無しのクライアントのみで確認できると思います。

**Comment by aspennn** [comment]
本件には関係ないですがLMLibraryの不具合も見つけたのでよろしくお願いします

**Comment by firis-games** [comment]
上記内容について下記バージョンで別の方からの報告で別途対応して公開しています。
https://github.com/firis-games/LittleMaidReengagedFirisPatch/releases/tag/ver.fp.055
そちらでは対応されているはずなのでver.fp.055をご利用ください。
